aws_region      = "ap-south-1"
profile         = "solarproj-sb"
environment     = "production"
cluster_name    = "solar-project-eks-cluster"
cluster_version = "1.32"
user_arn        = "arn:aws:iam::847551001400:user/agtsourabh" # Replace with your IAM user ARN
role_arn        = "arn:aws:iam::847551001400:role/eksclusterrole" # Replace with your IAM role ARN
policy_arn      = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy" # EKS Cluster Admin Policy ARN
ebs_csi_driver_version = "v1.49.0-eksbuild.1" # Latest as of Dec 2024
remove_existing_gp2_default = true # Set to true to remove default annotation from existing gp2 StorageClass