aws_region      = "ap-south-1" # String type value
profile         = "solarproj-sb"
environment     = "development"
cluster_name    = "solar-project-eks-cluster"
cluster_version = "1.32"
node_min_size   = 2 # Number type value
node_max_size   = 3 
node_desired_size = 2
node_instance_types = ["t3a.large"] #List type value
node_capacity_type  = "SPOT" # "ON_DEMAND" or "SPOT"
disk_size       = 25
disk_type       = "gp3"
disk_iops       = 3000
disk_throughput = 125
user_arn        = "arn:aws:iam::847551001400:user/agtsourabh" # Replace with your IAM user ARN
role_arn        = "arn:aws:iam::847551001400:role/eksclusterrole" # Replace with your IAM role ARN
policy_arn      = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy" # EKS Cluster Admin Policy ARN
ebs_csi_driver_version = "v1.49.0-eksbuild.1" # Latest as of Oct 2025
remove_existing_gp2_default = true # Set to true to remove default annotation from existing gp2 StorageClass